/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Accumulator_agentPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d accumulator_agent accumulator_agent
# Hostname: novo
# Current working directory: /home/leo/Desktop/Workspace/fontanelz
# Creation date: 2026-03-23T23:26:12.312+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include "negotiator.hpp"
#include <chrono>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "accumulator_agent"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using namespace chrono;

#define PERIOD 1
#define MAX_CAPACITY 2000.0 // [Wh]
#define MAX_CHARGE_POWER 3000.0 // [Wh]
#define MAX_DISCHARGE_POWER 3000.0 // [Wh]
#define EFFICIENCY 0.75


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Accumulator_agentPlugin : public Filter<json, json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    // Do something with the input data
    // listen just for sources
    _negotiator.listen(input, topic);

    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();

    auto now = steady_clock::now();
    duration<double> elapsed = now - _last_time;
    _last_time = now;
    _time_accumulator += elapsed.count();

    while(_time_accumulator >= PERIOD){


      _covariance = max(0.1, _negotiator.get_other_covariances());
      _input_power = _negotiator.get_other_powers() - _negotiator.get_tot_requests();

      _input_power = _input_power / (_negotiator.how_many_accumulators() + 1); // +1 for the node itself

      _input_power = std::clamp(_input_power, 0.0, MAX_CHARGE_POWER);

      double delta = _input_power * PERIOD / 3600.0;
      _energy_stored += delta * EFFICIENCY;

      if(_energy_stored > MAX_CAPACITY){

        _energy_stored = MAX_CAPACITY;
      }

      _soc = (_energy_stored / MAX_CAPACITY) * 100.0;
      double max_pp = 0.1;
      if(_soc > 15.0){
        max_pp = MAX_DISCHARGE_POWER;
      }

      _negotiator.set_cov(_covariance);
      _negotiator.set_pmax(max_pp);

      if(_input_power > 0){
        _output_power = 0.0;
      }
      _negotiator.update_proposal();

      if(_negotiator.get_stab_flag()){

        _output_power = _negotiator.get_proposed_power();


        double discharged = (_output_power * PERIOD) / 3600.0;
        _energy_stored -= discharged / EFFICIENCY;


        cout << "\rErogating [" << _output_power << "W] while SOC: [" << _soc << "]" << "\t cov: " << _covariance << "\033[K" << endl;
        
      } else{

        cout << "\rNegotiation in progess  \033[K" << endl;
      }

      out = _negotiator.speak(); // proposed power
      // require exceeding power from sources, if != 0 (check already done)
      out["request"] = _input_power;

      _time_accumulator -= PERIOD;  
      
      if (!_agent_id.empty()) out["agent_id"] = _agent_id;
      return return_type::success;
    }    

    // load the data as necessary and set the fields of the json out variable

    // This sets the agent_id field in the output json object, only when it is
    // not empty
    return return_type::retry;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    _negotiator.set_acc(true);
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  Negotiator _negotiator = Negotiator(0.01, 0.0);
  double _input_power = 0.0;
  double _output_power = 0.0;
  double _covariance = 0.01;

  steady_clock::time_point _last_time = steady_clock::now();
  double _time_accumulator = 0.0;

  // accumulator
  double _energy_stored = 0.0;
  double _soc = 0.0;

  int _active_accumulators = 0;

};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Accumulator_agentPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Accumulator_agentPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

